### ISSUE TITLE
alt-w requires a ctrl-g afterward to deselect

### ISSUE THREAD

**Issue by artagnon** [avendael/atomic-emacs#101]
As discussed in #84, deselecting after a copy is desirable and should atleast be an option.

**Comment by oggy** [comment]
Hi @artagnon.

Does this relate to alt-w or cmd-c? The subject suggests the former, but I don't see this behavior: alt-w copies to kill ring and deselects, like emacs.

cmd-c is the regular built-in copy, which does not deselect. If this is the command you want to have deselect, what do you think of proposing this option to the Atom project?

**Comment by artagnon** [comment]
Hi @oggy,

I basically re-bound <kbd>alt-w</kbd> to <kbd>cmd-c</kbd>, because I can't have one keybinding for system clipboard and another for the atomic-emacs clipboard. What do we propose exactly? Deselect after copy + hook into kill-ring?

**Comment by oggy** [comment]
Ok fair point; I'm swayed. I'll have something in soon.

**Comment by artagnon** [comment]
@oggy Actually, `clipboard-plus` is pretty awesome. You can just integrate that; no need to re-implement kill-ring.

**Comment by oggy** [comment]
Glad you found a solution that works for you.

I'm proceeding as planned regardless. There's no need to reimplement the kill ring for this -- just a setting to toggle whether the built-in copy/cut commands invoke the kill ring ones.

(Also looking at the pasting/yanking dichotomy separately.)
