### ISSUE TITLE
v0.9.2: Cursor moving by two spaces and two lines in 

### ISSUE THREAD

**Issue by lzkelley** [avendael/atomic-emacs#107]
OSX: 10.11.2
atom: 1.9.0-beta0
atomic-emacs: 0.9.2

With v0.9.2 installed, moving the cursor between letters or lines jumps by two spaces instead of one.  Disabling atomic-emacs fixes the problem.

![atomic-emacs-err-1](https://cloud.githubusercontent.com/assets/3839265/16178212/fe8ce1e2-360f-11e6-91a6-a308ffd90d03.gif)

**Comment by oggy** [comment]
If you reload the window (cmd-shift-p window:reload) and re-enable, does it fix it?

I think it's related to upgrading the package. Just pushed a fix to master which might help prevent it in future.

**Comment by lzkelley** [comment]
Hmm, interesting.  Yeah that does fix it for me, thanks!
