### ISSUE TITLE
C-x C-f can't create new files

### ISSUE THREAD

**Issue by nloveladyallen** [avendael/atomic-emacs#108]
In Emacs, C-x C-f foo RET will open a new file foo if foo does not exist. With Atomic Emacs, C-x C-f foo RET will do nothing (Atom remains in the current buffer) if foo does not exist.

**Comment by oggy** [comment]
Thanks for the suggestion. I suppose the fuzzy finder does not strictly emulate emacs, but I think most people find it more useful. Probably worth making this an option.

FWIW [advanced-open-file](https://atom.io/packages/advanced-open-file) is a pretty good implementation of emacs' find-file -- just need to set the keybinding yourself.

**Comment by k1-hedayati** [comment]
@oggy is there a policy for not adding third-party packages to `atomic-emacs`?
I believe people install this package in order to get emacs experience in atom, so using `advanced-open-file` is a step toward users goal

**Comment by oggy** [comment]
I'm resolving this for now by adding a setting to use advanced-open-file for ctrl-x ctrl-f if it's installed, plus adding a note to the readme.

Atom doesn't have a great mechanism for optional package dependencies like this. For the reasons discussed [here](https://github.com/atom/apm/issues/288), I don't think including the other package in this one, or as an npm dependency, is a good idea (and the services mechanism discussed there doesn't seem appropriate either).

I'm thinking ideal might be some sort of post-install notification, but I don't see a way to do that, so this seems like a reasonable compromise.
