### ISSUE TITLE
Underscores in forward/backward sexp

### ISSUE THREAD

**Issue by adamboche** [avendael/atomic-emacs#112]
Not sure about others, but in my emacs, M-f seems to treat underscores like spaces, which is useful in some programming styles. Atomic emacs doesn't seem to do this, jumping across this_whole_variable. Is this an intended divergence from emacs?

**Comment by oggy** [comment]
Hi @adamboche,

This is taken from Atom's "Non Word Characters" settings ("Editor" tab of the settings pane). Just add the underscore here.
