### ISSUE TITLE
M-< and M-> to move to the beginning and end of buffer

### ISSUE THREAD

**Issue by Yutsa** [avendael/atomic-emacs#113]
I looked a bit and the `M-<` and `M->` keybindings are not implemented. 

`M-<` goes back to the beginning of the buffer and `M->` to the end of the buffer. I wanted to create a patch but I don't know CoffeScript so I guess someone else will have to do it.

But it looks like a pretty simple command to add.

**Comment by demmer** [comment]
FWIW I have the following in my keymap which does the trick:

```
  'cmd-<' : 'core:move-to-top'
  'cmd->' : 'core:move-to-bottom'
```

**Comment by Yutsa** [comment]
Yes I have it to 
```
  'alt-<': 'core:move-to-top'
  'alt->': 'core:move-to-bottom'
```

But unfortunately it does nothing when I press it. I don't know why.

I have a AZERTY keyboard if that's relevant and I'm on Debian

**Comment by oggy** [comment]
Atomic Emacs does bind these commands, and they're working for me.

If you're still seeing this, try running `key-binding-resolver:toggle` to see if the command is being shadowed by another package.

**Comment by oggy** [comment]
Closing this as stale.
