### ISSUE TITLE
goto-line not working properly when defined

### ISSUE THREAD

**Issue by t1mg** [avendael/atomic-emacs#114]
The goto-line feature in emacs (usually invoked with M-g g) is not working properly with atom-emacs under Linux.
I defined
`'alt-g g': 'go-to-line:toggle'`
to my keymap, but that didn't work. 
Manually invoking the Go-To-Line feature via the Command Palette works fine.

I see it's defined in the project's keymap.cson for .platform-darwin and .platform-win32, but apparently even if I add a section for .platform-linux with this command in it it does not have an effect.

UPDATE:

I got it to work when putting it under the atom-workspace class, so:

'atom-workspace':
  'alt-g g': 'go-to-line:toggle'

**Comment by oggy** [comment]
Thanks for reporting this; I finally pushed a fix.

Note that the core `open-on-github` package uses `alt-g g`. Both Emacs & Atomic Emacs bind `go-to-line` to both `alt-g g` and `alt-g alt-g`, however, so I suggest using the latter binding.
