### ISSUE TITLE
Rectangles

### ISSUE THREAD

**Issue by drexell0680** [avendael/atomic-emacs#118]
Great package for atom!  As a request for additional functionality, I find myself frequently wishing for the rectangle functionality (C-x r).  
https://www.gnu.org/software/emacs/manual/html_node/emacs/Rectangles.html

**Comment by oggy** [comment]
Hi @drexell0680,

The atomic-emacs commands generally play well with Atom's multiple cursors. e.g. to select a "rectangle", you could:

 * create a cursor for each row: `ctrl-shift-up/down`
 * set mark: `ctrl-space`
 * move to other side: left/right or `ctrl-f`/`ctrl-b`. the selections don't have to stay aligned, e.g. if you use `alt-f` to move by words
 * kill: `ctrl-w`

You can also move over and yank it (`ctrl-y`) somewhere, although if you leave multiple cursor mode, the cursor-local kill rings (i.e. the text you killed) will disappear too.

How much does this accomplish what you need? I'm not opposed to adding something that behaves more like emacs' rectangle commands; I just find this generally does what I need. I was hardly a power user of emacs' rectangle commands, though.

**Comment by drexell0680** [comment]
This is exactly what I was looking for, thanks.
