### ISSUE TITLE
Delete blank lines (ctrl-x ctrl-o)

### ISSUE THREAD

**Issue by dannymidnight** [avendael/atomic-emacs#119]
Thanks for the great work getting this package going. I have a feature request for [deleting blank lines](https://www.gnu.org/software/emacs/manual/html_node/emacs/Blank-Lines.html) `ctrl-x ctrl-o`. Turns out it's something I use all the time!

If I get time I'll jump in and contribute but thought I'd put it up here for anyone else if it's of interest.

**Comment by oggy** [comment]
Hi @dannymidnight,

I think this would be a great addition. Feel free to send a PR, otherwise I'll try to get around to it soon. `just-one-space`, which does the same thing for horizontal space, might serve as a useful guide.
