### ISSUE TITLE
Problem with Ctrl+k kill-line

### ISSUE THREAD

**Issue by jeanpul** [avendael/atomic-emacs#123]
Thanks for this package !

When I use Ctrl-k then the line is deleted regardless of the cursor position but
in emacs terminology Ctrl-k is kill line to end so this do not match this emacs keybinding

The exact rule should be 
atom-workspace atom-text-editor': 'ctrl-k': 'editor:cut-to-end-of-line'

**Comment by oggy** [comment]
Hi,

I'm not seeing this behavior myself. What do you see bound to the key when you run `key-binding-resolver:toggle` and then type `ctrl-k`?

**Comment by jeanpul** [comment]
Hi,

This is working now after the update, thanks a lot
