### ISSUE TITLE
Only a subset of keybinding are enabled

### ISSUE THREAD

**Issue by proudot** [avendael/atomic-emacs#124]
Hi there, thanks for that very interesting package. 

I only have subset of keybinding active. For example, Ctrl-j is not set to new line. Ctrl-n or Ctrl-p are working but some more advanced binding are not activated per-default. Any idea ? 

Best, 
Proudot.

**Comment by oggy** [comment]
What do you see if you run `key-binding-resolver:toggle` and then type these keystrokes?

**Comment by oggy** [comment]
I'm guessing you're on Windows or Linux. I just pushed a fix for some bindings there.
