### ISSUE TITLE
Build is broken

### ISSUE THREAD

**Issue by MartyGentillon** [avendael/atomic-emacs#129]
on 16abf3853bb2907b5b2a0ff6e011509024323255

```
> apm test
....................F.....................................................................................................................
..........................................................................................................................................
............................................................

AtomicEmacs
  atomic-emacs:forward-sexp
    it moves all cursors forward one symbolic expression
      Expected '  aa
[0](bb cc)[1]
' to equal '  aa[0]
(bb cc)[1]
'.
        at .<anonymous> (file:///C:/Users/Marty/Documents/GitHub/atomic-emacs/spec/atomic-emacs-spec.coffee:137:38)


Finished in 9.732 seconds
336 tests, 422 assertions, 1 failure, 0 skipped


Tests failed
```

**Comment by MartyGentillon** [comment]
Running on windows 10 creators update.

**Comment by MartyGentillon** [comment]
Based on bisecting, the first commit with this behavior is 66e312bbfe75179504c9ae7b624d199d41a53ae7.  Interestingly before that, atom was different enough that it is possible that this test still failed.

**Comment by MartyGentillon** [comment]
Some further test strings which happen to pass

"[0]  aa (dd)\n[1](bb cc)\n" -> "  aa[0] (dd)\n(bb cc)[1]\n"
"[0]  aa dd\n[1](bb cc)\n" -> "  aa[0] dd\n(bb cc)[1]\n"

yet doesn't pass.  The bug has something to do with newlines.
"[0]  aa\n (dd)\n[1](bb cc)\n" -   aa\n[0] (dd)\n(bb cc)[1]\n"

**Comment by oggy** [comment]
Thanks!

I'm pretty certain this did work when it was written. A while back I traced it down to a bug (or at least undocumented change) in the core text-buffer package. IIRC it changed how `\s` is handled with respect to newlines. I had started trying to fix it there but never got around to finishing it.

In the meantime if you can find a simple workaround that'd be awesome.

**Comment by MartyGentillon** [comment]
Found a fix.  I will include it with my pull request for https://github.com/avendael/atomic-emacs/issues/103

**Comment by MartyGentillon** [comment]
apparently:

```javascript
"\n".match(new RegExp("\W", "gmi"))
-> null
'\n'.match(/[\W]/gim)
-> ["\n"]
"\n".match(new RegExp("[\W\n]", "gmi"))
["\n"]
```

So, our bug lies someplace in native code.....

**Comment by MartyGentillon** [comment]
And by native code, I mean in Chromium and Chrome.  The same behavior is demonstrated in my web browser's dev tools.

**Comment by MartyGentillon** [comment]
Found my mistakes... now I have to see if I can find the underlying bug.

**Comment by MartyGentillon** [comment]
This time I have got it right.  The difference is that atom text-buffer considers /\W/ a single line regular expression, while /[\W\n]/ is a multi-line regular expression as determined by the regular expression on text-buffer/lib/helpers.js line 6.

**Comment by MartyGentillon** [comment]
Apparently I am on a slightly old version, but the bug is still there. https://github.com/atom/text-buffer/blob/master/src/helpers.js#L3

**Comment by MartyGentillon** [comment]
Root cause: https://github.com/atom/text-buffer/issues/226

**Comment by MartyGentillon** [comment]
Workaround in https://github.com/avendael/atomic-emacs/pull/130

**Comment by oggy** [comment]
Fix was merged. Thanks @MartyGentillon !
