### ISSUE TITLE
Easy way to change Meta key to Command?

### ISSUE THREAD

**Issue by aguynamedben** [avendael/atomic-emacs#131]
Hi, thanks for the time you spend working on this great project. I'm very excited to use it. I have a question that I can't find an answer to in the docs.

In my usual Emacs config file I have this:
```lisp
;; set keys for Apple keyboard, for emacs in OS X
;; http://ergoemacs.org/emacs/emacs_hyper_super_keys.html
(setq mac-command-modifier 'meta) ; make cmd key do Meta
(setq mac-option-modifier 'super) ; make opt key do Super
(setq mac-control-modifier 'control) ; make Control key do Control
(setq ns-function-modifier 'hyper)  ; make Fn key do Hyper
```

This config means that on my Mac I'm accustomed to hitting Command-f (Meta-f) to go forward a word, but now I have to hit Option-f (alt-f in Atom terms).

In Atomic Emacs is there an easy way to change the Meta key to use Command instead of Option? I realize I can go through and override each individual entry in the keymap, but I'm wondering if there's a more easy "correct" way to do this.

**Comment by oggy** [comment]
Hmm, I don't know of a great way to do this in Atom.

What I do is just swap the Command and Option keys at the OS level. I get lots of funny looks for this, but this way I get to use Command for navigation across other apps like terminals and browsers too.

Failing that perhaps you could hit up the Atom Discourse or Slack group for ideas.

**Comment by aguynamedben** [comment]
What I ended up doing (as an Atom noob wanting to try it out more) to change Emacs Meta to macOS Command.

1. Open Atom
2. Go to Atom > Keymap...
3. Copy https://github.com/avendael/atomic-emacs/blob/master/keymaps/atomic-emacs.cson into your keymayp.cson
4. Change all instances of `alt` to `cmd`.
5. Comment out `'cmd-c': 'atomic-emacs:capitalize-word-or-region'` because you want Command-C to still copy (this previously was `alt-c` but in Step 4 you changed it to `cmd-c`, creating the conflict).
6. Comment out `'cmd-v': 'atomic-emacs:scroll-down'` because you want Command-V to still paste (this previously was `alt-v` but in Step 4 you changed it to `cmd-v`, creating the conflict).

Optional:
- I added `'alt-h': 'fuzzy-finder:toggle-buffer-finder'` in the `'atom-workspace atom-text-editor'` section and the `'atom-workspace'` section to mimic my helm-projectile settings (overwrites the default Atom `alt-h` keybinding to `editor:delete-to-beginning-of-word`). You have to add it to both sections to have Alt-h open a file from (1) a pane that already has a file open, and (2) a pane that doesn't already have a file open (i.e. a newly opened pane).
- I also deleted the `linux` and `win32` platform references from keymap.cson since I just use Atom on macOS and want the file to be digestible.
- I added `'shift-right': 'window:focus-next-pane'` and `'shift-left': 'window:focus-previous-pane'` to simulate [Wind Move](https://www.emacswiki.org/emacs/WindMove) moving between panes

Tips:
- To see what is currently bound, go to Atom > Preferences... > Keybindings and search for a keybinding. Hit the copy icon next to a specific keybinding, then you can paste it into your keymap.cson to see where it belongs.
