### ISSUE TITLE
How to install?

### ISSUE THREAD

**Issue by gubatron** [avendael/atomic-emacs#136]
Copied and pasted the bindings from the readme into the file shown on Atom > KeyMaps.

Opened a new buffer, and nothing.

Now I'll have to google on how to install keybindings, it'd be awesome if you had at least one paragraph explaining how to install this on Atom on your README.md, would save a lot of new users some time.

Cheers

**Comment by oggy** [comment]
It's installed like any Atom package: on the settings pane (Cmd-, on a mac) -> Install tab -> search for "atomic-emacs" -> click "Install"

Or if you have the "apm" utility on the command line, you can just do `apm install atomic-emacs`.

Hope this helps!

**Comment by gubatron** [comment]
https://github.com/avendael/atomic-emacs/pull/137

**Comment by gubatron** [comment]
Thanks!
