### ISSUE TITLE
atomic-emacs:find-file not working in split panes w/o open tabs

### ISSUE THREAD

**Issue by jnmandal** [avendael/atomic-emacs#138]
It used to be I could use: "C-x 3", then "C-x C-f"m and find a file I wanted to open in a new pane. Recently, this stopped working. Now when I split a pane, I cant use the `atomic-emacs:find-file` command until I open a tab in that pane.

**Comment by ashkang** [comment]
Same problem here. I can no longer use find-file functionality.

**Comment by oggy** [comment]
Fixed in 0.12.1.
