### ISSUE TITLE
ctrl-w doesn't' delete word.

### ISSUE THREAD

**Issue by SeanSilke** [avendael/atomic-emacs#139]
Come from bash cli I expected ctr-w to delete word but it doesn't.
It may occur from third plugin interaction but i was not able to detect it.

**Comment by gsingh93** [comment]
ctrl-w is not delete word, it's kill-region like it's supposed to be. If you want to kill the next word, you can use alt-d.

**Comment by SeanSilke** [comment]
@gsingh93 Thank, my fault.
