### ISSUE TITLE
Emacs style cursor not showing on OSX

### ISSUE THREAD

**Issue by kc-beard** [avendael/atomic-emacs#141]
Atom: 1.19.2
OSX: 10.12.6

The Emacs-style block cursor doesn't show. I tried adding: ```useEmacsCursor: true``` to config, but that didn't help.

**Comment by oggy** [comment]
I don't believe there was ever any such option in atomic-emacs. It looks like [this](https://atom.io/packages/block-cursor) might give you what you want, though.
