### ISSUE TITLE
TAB should act more like Emacs TAB and run indent-for-tab-command

### ISSUE THREAD

**Issue by b-jazz** [avendael/atomic-emacs#144]
Basically if I have the following python code:

    def foobar():
        print('foobar')

and I have the cursor on the second line, in the 0 column (under the 'd' in `def`), and I hit tab, a regular tab will be inserted and I'll have the following:

    def foobar():
            print('foobar')

in Emacs, it will run `indent-for-tab-command` and simply reindent the line and bring the cursor to the 4 column (on the 'p' in `print`) instead of inserting extra spaces or tabs. Subsequent presses of TAB will outdent(?) the line and cycle back around to properly indented.

**Comment by oggy** [comment]
Thanks! Agreed.
