### ISSUE TITLE
feature request: kill-paragraph

### ISSUE THREAD

**Issue by jpivarski** [avendael/atomic-emacs#150]
After using Emacs for 25 years, I'm switching to Atom. I've found your atomic-emacs to be indispensable, though one of the commands I find I'm missing is kill-paragraph. I noticed that I had it bound to a custom key in Emacs (so I don't know what the original key was, if any), but if you have a kill ring and forward-paragraph, it should be possible to combine them to emulate kill-paragraph, right?

**Comment by oggy** [comment]
Yes! It needs documenting (beyond the way-too-low-key changelog entry), but you can consume AtomicEmacs as a service and extend it. For example, you could add subword navigation like this:

init.coffee:

```coffeescript
atom.workspace.packageManager.serviceHub.consume "atomic-emacs", "^0.13.0", (service) ->
  window.emacs = service

forwardSubword = (event) ->
  emacsEditor = emacs.getEditor(event)
  emacsEditor.moveEmacsCursors (emacsCursor) ->
    emacsCursor.skipNonWordCharactersForward()
    emacsCursor.cursor.moveToNextSubwordBoundary()

backwardSubword = (event) ->
  emacsEditor = emacs.getEditor(event)
  emacsEditor.moveEmacsCursors (emacsCursor) ->
    emacsCursor.skipNonWordCharactersBackward()
    emacsCursor.cursor.moveToPreviousSubwordBoundary()

atom.commands.add 'atom-text-editor', 'me:forward-subword', (event) -> forwardSubword(event)
atom.commands.add 'atom-text-editor', 'me:backward-subword', (event) -> backwardSubword(event)
```

keymap.cson:

```coffeescript
'atom-text-editor':
  'ctrl-left': 'me:backward-subword'
  'ctrl-right': 'me:forward-subword'
```

You'll need to crawl the source for now to figure out what methods are available on an [EmacsEditor][emacs-editor] and [EmacsCursor][emacs-cursor], but hopefully it's pretty easy to follow.

[emacs-editor]: https://github.com/avendael/atomic-emacs/blob/master/lib/emacs-editor.coffee
[emacs-cursor]: https://github.com/avendael/atomic-emacs/blob/master/lib/emacs-cursor.coffee

As far as adding it to AtomicEmacs goes, I'd take a patch that added it if it supported multiple cursors like the other commands. Looks like GNU emacs doesn't ship with a key binding by default, so it'd be similarly unbound by default in AtomicEmacs.
