### ISSUE TITLE
Exception: t.getModel is not a function

### ISSUE THREAD

**Issue by jpivarski** [avendael/atomic-emacs#151]
This is triggered differently from #89, but otherwise looks similar.

I've verified that the bug occurs if and only if atomic-emacs is enabled (e.g. if atomic-emacs is the only package, the bug occurs and if all packages except atomic-emacs are enabled, the bug does not occur).

(By the way, this package is great! It's helped me transition from 25 years of Emacs to Atom this year. Thank you very much!)

[Steps to reproduce:]

1. select something
2. `find-and-replace:select-next`

**Atom**: 1.39.1 x64
**Electron**: 3.1.10
**OS**: Pop!_OS 18.04
**Thrown From**: Atom Core

### Stack Trace

Uncaught TypeError: t.getModel is not a function

```
At /usr/share/atom/resources/app/static/<embedded>:11

TypeError: t.getModel is not a function
    at /usr/share/atom/resources/app/static/<embedded>:11:182763
    at HTMLDivElement.find-and-replace:select-next (/usr/share/atom/resources/app/static/<embedded>:11:183154)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:348736)
    at KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app/static/<embedded>:11:1248155)
    at KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app/static/<embedded>:11:1244289)
    at WindowEventHandler.handleDocumentKeyEvent (/usr/share/atom/resources/app/static/<embedded>:11:283942)
```

### Commands

```
     -3:32.4.0 command-palette:toggle (input.hidden-input)
     -3:30.3.0 core:confirm (input.hidden-input)
     -3:30.3.0 find-and-replace:select-next (input.hidden-input)
     -3:17.8.0 atomic-emacs:isearch-forward (input.hidden-input)
     -3:15.3.0 command-palette:toggle (input.hidden-input)
     -3:13.4.0 core:confirm (input.hidden-input)
     -3:13.4.0 find-and-replace:select-next (input.hidden-input)
     -0:08.3.0 atomic-emacs:isearch-forward (input.hidden-input)
     -0:04.8.0 find-and-replace:select-next (input.hidden-input)
```

### Non-Core Packages

```
advanced-open-file 0.16.8 
atom-scale-factor 0.2.1 
atomic-emacs 0.14.0 
ctrl-dir-scroll 0.2.5 
Hydrogen 2.10.3 
hydrogen-launcher 1.2.2 
language-latex 1.2.0 
latex 0.50.2 
maximize-panes 0.2.0 
pdf-view 0.71.0 
platformio-ide-terminal 2.9.3 
sync-settings 0.8.6 
teletype 0.13.4 
```

**Comment by oggy** [comment]
Thanks for reporting, @jpivarski !

I'm unable to repro this using 1.40.0 x64, and given that I only see core-looking stuff in that stack trace, I'm going to guess that it was an Atom bug that's been fixed.

Here's what I tried:

 * Moved my ~/.atom aside.
 * Installed the mentioned packages
 * Opened Atom (atomic-emacs project)
 * Double-clicked a word
 * `M-x find-and-replace:select-next`

Worked fine.

Tried selecting using `ctrl-space` and arrowing around instead of selecting the word by mouse. Worked.

Tried subsequent `find-and-replace:select-next`s, also worked as expected.

I just realized you're using Linux, so let me know if you're still seeing it after upgrading Atom & I can try that too. That just takes a bit more work to run through on my end.

**Comment by jpivarski** [comment]
Aha! The difference between what we're doing is this:

   * Double-clicked a word

When I select text with a forward incremental search (the way I usually do; habit from Emacs because you can grow the selection with ctrl-w), and then do `M-x find-and-replace:select-next`, I get the stack trace mentioned above.

When I select text any other way, with the mouse or shift-arrow key, and then do `M-x find-and-replace:select-next`, there's no stack trace: it works as it's supposed to.

The incremental search is putting the editor into a state in which it can't handle select-next. I've upgraded to Atom 1.40.0 and it's still true. I doubt this is related to the Linux platform because it's a Javascript stack trace—that ought to be the same on all platforms.

If you try it with the incremental search, do you see the stack trace?

**Comment by oggy** [comment]
I do! Thanks for clarifying.

I'll push a fix to prevent the error, although it won't make `find-and-replace:select-next` select what you've searched for using isearch. For now at least, `find-and-replace` and our isearch are two distinct systems. If `select-next` would do its search based on what's currently selected then it'd work, but it's based on `find-and-replace`'s current search string, which is distinct from isearch's search string. I'll think on it, but this is probably tricky to solve.
