### ISSUE TITLE
Change in auto-indent behavior on hitting `tab`

### ISSUE THREAD

**Issue by lzkelley** [avendael/atomic-emacs#153]
Previously when I hit `tab` atom would auto-indent to it's guess of the correct indentation given the context, and then subsequent `tab`s would indent further.  A while ago (~3 weeks), this changed to **only** moving to the auto-indent location (i.e. subsequent `tab`s have no effect).

I'm not sure this is caused by something in this package *per se*, but by disabling atomic-emacs the previous behavior was restored.

**Comment by oggy** [comment]
It's intentional (#144), as I think this more closely mimics Emacs behavior for most editing modes.

You can change this back by defining a custom binding for tab. For example, this in your `~/.atom/keymap.cson` (or the JSON-equlivalent for json):

```
'atom-text-editor:not(.autocomplete-active):not(.mini)':
  'tab': 'editor:indent'
```
