### ISSUE TITLE
Can you add keybindings for go to start/end of file?

### ISSUE THREAD

**Issue by vvanirudh** [avendael/atomic-emacs#156]
Typically in emacs I use `ctrl+x [` and `ctrl+x ]` to go to the start/end of file. This don't seem to work in atomic-emacs. Any chance they can be added?

**Comment by jmtoniolo** [comment]
The core supports this. Just bind a keystroke to `core:move-to-top` and 'core:move-to-bottom'. The package also automatically binds these to alt-> and alt-<.

**Comment by vvanirudh** [comment]
Thanks!
