### ISSUE TITLE
Linux keybindings

### ISSUE THREAD

**Issue by ivan-krukov** [avendael/atomic-emacs#21]
The time has come when atom is available on other platforms.
There is a small subset of key bindings that are currently not implemented for a happy emacs time.
I will just point out the more obvious ones that are shadowed by system key bindings:
* 'ctrl-a': 'core:move-to-first-character-of-line'
* 'ctrl-e': 'core:move-end-of-screen-line'
* 'ctrl-k': 'core:delete'
The above are not configured automatically when added to keymap.cson. Is there a way to change the priority of key binding association (or unbind the core ones altogether)?

**Comment by olanod** [comment]
+1 linux user here

**Comment by avendael** [comment]
Merged [PR](https://github.com/avendael/atomic-emacs/pull/46) that adds ctrl-a and ctrl-e for Linux. I hope it helps.

**Comment by bassu** [comment]
@mndrix and @otavio's configs came pretty handy as I just had to switch back to the PC after accidently pouring Coke into my Mackbook, LOL.

It would have been much better if Linux GUIs provided Emacs'ish keybindings by default like OSX does. The only place where ctrl-a, ctrl-e, ctrl-k and y works is in Bash.

**Comment by mivade** [comment]
For some reason, C-e does not work for me on Linux (the default `find-and-replace:use-selection-as-find-pattern` is always activated instead). C-a works just fine, though.

**Comment by bassu** [comment]
@mivade Use keybinding resolver to see which rule it points to, then override with a rule with which has higher [CSS specifity](http://specificity.keegan.st/)

**Comment by mivade** [comment]
@bassu Thanks for the pointers. I don't really know how to do that yet, and it is seemingly more complicated than I hoped. Simply trying to unset C-e keybindings in `keymap.cson` hasn't appeared to work either (although I could be doing that incorrectly):

```
'.platform-win32, .platform-linux':
    'ctrl-e': 'unset!'
```

Maybe I need to unset even more bindings like in @mndrix's example.

**Comment by bassu** [comment]
@mivade The way you're doing it now, it'll take a lot of time for you to figure it out because different key sequences act differently in different file modes, packages, etc. You need to resolve the key sequence with keybinding resolver. Go to Packages > Keybinding Resolver > Toggle and see what rule it's calling. Then disable that rule in `keymap.cson` with `unset`. After that add a new one with more specificity weight.

**Comment by oggy** [comment]
Closing this, as I'm assuming the original issue has been resolved. Feel free to reopen if you think there's anything else atomic-emacs should be doing here.
