### ISSUE TITLE
Previous Line Very Slow

### ISSUE THREAD

**Issue by LukeMauldin** [avendael/atomic-emacs#36]
Using atomic-emacs 0.35 I encountered the error where Ctrl-P/Ctrl-N would skip lines.  After upgrading to 0.36, I no longer encounter the skipping line problem, but Ctrl-P is very slow, maybe 2 seconds to navigate to the previous line  Ctrl-N is very fast and navigates to the next line immediately.  Atom version is 0.166 on OSX.

**Comment by avendael** [comment]
This should now be fixed with the latest version. Please update and verify.

**Comment by LukeMauldin** [comment]
Fixed
