### ISSUE TITLE
ctrl-n, meta-b, meta-f, etc. stop working

### ISSUE THREAD

**Issue by mndrix** [avendael/atomic-emacs#37]
Sometimes all the atomic-emacs keybindings which move point stop working.  I press the key binding and point stays right where it is.  According to the Key Binding Resolver, the key binding is still bound to the proper atomic-emacs command but nothing happens.

If I disable and re-enable the atomic-emacs package, the key bindings start working again.  Unfortunately, after doing this a few times these key bindings start repeating themselves: meta-b goes backwards two words.  At this point, I have to reload Atom to get normal behavior again.

I'm using atomic-emacs 0.3.6 with Atom 0.169.0 on OS X 10.10.1

**Comment by aitherios** [comment]
I'm having the same issue with atomic-emacs 0.3.6 with Atom 0.170.0 on OS X 10.10.1

**Comment by tony-kerz** [comment]
ya, me too. i have had to resort to disabling the package and using default atom key-bindings which apparently support some subset of emacs commands, but the missing ones are really throwing me off.

**Comment by deanmalmgren** [comment]
I'm having the problem as well. In addition, I've had an issue where my left/right arrow keys stop working altogether in the middle of an atom session. Restarting atom seems to fix the problem temporarily.

@tony-kerz As a workaround, I've commented out [those lines](https://github.com/avendael/atomic-emacs/blob/master/keymaps/atomic-emacs.cson#L57-L60) in the keymap.cson file that I have locally. I did the same for the [ctrl+{p,n,f,b} commands](https://github.com/avendael/atomic-emacs/blob/master/keymaps/atomic-emacs.cson#L14-L17), too. This makes it so I can at least use the rest of the keyboard shortcuts.

**Comment by mndrix** [comment]
When this happens, if I press ctrl-n (for example) neither `atomic-emacs:next-line` nor `atomicEmacs.nextLine` are called.  I added logging for these commands and the logging stops appearing as soon as ctrl-n breaks.

**Comment by nkwhr** [comment]
I'm having this problem when I split panes. Same as deanmalmgren, left/right arrow keys stop working too. Hope it gets fixed.

**Comment by mrhota** [comment]
Happens for me every time I split panes (either C-x 2 or from the View menu).

Atom 0.187.0, Mac OS X 10.10.2

**Comment by avendael** [comment]
This should now be fixed with the latest version. Please update and verify.
