### ISSUE TITLE
Fix deprecation warnings in Atom v 0.174.0

### ISSUE THREAD

**Issue by sol1dus** [avendael/atomic-emacs#39]
- Use the `atom-text-editor` tag instead of the `editor` class.
- Use the selector `atom-text-editor[mini]` to select mini-editors.
- Use the selector `atom-panel.right` instead of the `panel-right` class.
- Use the selector `atom-panel` instead of the `tool-panel` class.

**Comment by sol1dus** [comment]
@avendael please assign this to me, gonna work on it next couple of days. thanks.

**Comment by avendael** [comment]
Thanks! I haven't cleared up a chunk of time to work on atomic-emacs as of the moment. I'm glad you're going to work on fixing these warnings :)

**Comment by mndrix** [comment]
I had been working on this before I saw this issue.  I've submitted my work in pull request #42  It fixes the selector deprecations mentioned by @sol1dus   It also fixes a bunch of other API deprecations.

**Comment by sol1dus** [comment]
@mndrix It's great, mate. Let's wait for merge @avendael

**Comment by avendael** [comment]
@mndrix PR is still open and it needs help. You might want to look into it @sol1dus ;)

**Comment by avendael** [comment]
PR is merged.
