### ISSUE TITLE
Add settings flag about using native keybindings for navigation keys

### ISSUE THREAD

**Issue by pavloo** [avendael/atomic-emacs#40]
As of #37, navigation keybindings are the source of numerous bugs. I propose adding checkbox in plugin's settings, smth like `use native keybindings for navigation keys (e. g. you are on OS X)`, which ultimately will disable those keybindings being overridden by plugin. If it's okay to u, @avendael , pls assign this feature to me. Thanks.

**Comment by avendael** [comment]
Please go ahead and submit a PR :) For some reason I can't assign created issues aside from myself.

**Comment by avendael** [comment]
It seems that you forgot to commit the settings UI. It works fine by setting the option through `config.cson` though, so I still pushed your PR to the new version.

**Comment by oggy** [comment]
This seems like a stale issue now. @avendael, @pavloo Good to close?
