### ISSUE TITLE
Can't move cursor in first panel after split.

### ISSUE THREAD

**Issue by ArnaudValensi** [avendael/atomic-emacs#43]
Hi,
I can't move cursor after doing 'ctrl-x 3', 'ctrl-o'.
I have atom 0.175.0 and atomic-emacs 0.3.7

Thank you

**Comment by jaydev** [comment]
+1, using atom 0.176.0 and atomic-emacs 0.4.0

**Comment by daisuke-meian** [comment]
+1
Me, too.
Atom 0.177.0, atomic-emacs 0.4.0

**Comment by pariser** [comment]
:+1: 
Atom 0.184.0
atomic-emacs 0.4.0
also using atom-pain-split 1.3.1, though its source doesn't seem like that would cause this problem.

**Comment by pariser** [comment]
No longer experiencing this issue after upgrading to atomic-emacs 0.5.0 (but experiencing #53 instead).

**Comment by avendael** [comment]
Thanks, looking into #53
