### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by aramiscd** [avendael/atomic-emacs#45]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/usr/local/share/atom/resources/app/src/atom.js:54:11)
Object.activate (/home/aramis/.setup/atom/packages/atomic-emacs/lib/atomic-emacs.coffee:30:9)
```

**Comment by avendael** [comment]
This should now go away with the latest version.
