### ISSUE TITLE
Overrides autocomplete ctrl-n & ctrl-p

### ISSUE THREAD

**Issue by LukeMauldin** [avendael/atomic-emacs#49]
If I enable atomic-emacs, and I set the setting "navigateCompletions: "ctrl-p,ctrl-n" in the "autocomplete-plus" package, then I cannot navigate the autocomplete list using ctrl-p,ctrl-n because Atomic Emacs overrides that keybinding and navigates lines.  I think the keymap selector for Atomic Emacs should be changed to not override "ctrl-p,ctrl-n" in the autocomplete dialog.

**Comment by avendael** [comment]
Thank you for your PR. I'll do a release tonight.
