### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by rocky-jaiswal** [avendael/atomic-emacs#51]
Thanks for building this tool. On latest version of atom, I get the following deprecation warnings -

![atomic-emacs](https://cloud.githubusercontent.com/assets/412883/6922549/45f717b2-d7cc-11e4-860b-ac222b0f7eaf.png)

If you can please have a look.

Thanks.

**Comment by avendael** [comment]
This should now go away with the latest version.
