### ISSUE TITLE
Remove mark doesn't remove mark

### ISSUE THREAD

**Issue by nathanjohnson320** [avendael/atomic-emacs#53]
When I use ctrl-space to start a mark and then hit escape or ctrl-g the mark doesn't go away. It continues to highlight until I restart atom.

**Comment by koki0702** [comment]
I have the same problem.

**Comment by LeartS** [comment]
Can confirm, it's really, really annoying.

**Comment by stjlaex** [comment]
Confirmed. Thought I had a perfect emacs replacement until this caught me out. Atom 0.189.0 on Linux if that helps.

**Comment by bassu** [comment]
Same problem since last update. Very annoying at the moment.

**Comment by LukeMauldin** [comment]
Confirmed on OSX, prevents from using package.

**Comment by nathanjohnson320** [comment]
I downgraded too. May look into it a fix if I get some free time

`apm install atomic-emacs@0.4.2`

**Comment by avendael** [comment]
I'm also looking into this, but it's quite strange since `cursor.clearSelection` doesn't seem to work.

**Comment by ytakano** [comment]
I have a same problem, too.

**Comment by bradens** [comment]
Same here :(

**Comment by olanod** [comment]
:+1:
