### ISSUE TITLE
atom-emacs-mode?

### ISSUE THREAD

**Issue by drozzy** [avendael/atomic-emacs#55]
What the diff between this package and atom-emacs-mode?
https://github.com/fuqcool/atom-emacs-mode

Which one implements more of emacs functionality with less problems?

**Comment by avendael** [comment]
I haven't tried `atom-emacs-mode` myself, so I can't really tell. But based from its description, it looks like it implements configuration options, which this package doesn't aim to do. This package simply provides emacs-like keybindings and functionalities, but the configuration options are still left to the atom platform.
