### ISSUE TITLE
Deprecated Atom APIs will be removed June 1st

### ISSUE THREAD

**Issue by benogle** [avendael/atomic-emacs#62]
Atom will no longer load this package after June 1st without changes. There are a couple deprecations on the latest version (`0.5.1`) of this package:

1. Use `activationCommands` instead of `activationEvents` in your package.json Commands should be grouped by selector as follows: ```json "activationCommands": { "atom-workspace": ["foo:bar", "foo:baz"], "atom-text-editor": ["foo:quux"] } ```
1. This method is deprecated on the model layer. Use `TextEditorElement::pixelPositionForBufferPosition` instead
1. Use TextEditor::moveRight() instead

Visit https://gist.github.com/benogle/6d09e295c84b717ef9b4 and search for your package name to see up-to-date deprecations.

If this package has been replaced by another package or functionality in core, please reply with this information.

See https://github.com/atom/atom/issues/6867 for more info. Thanks!

**Comment by avendael** [comment]
Thanks for letting us know. Merged https://github.com/avendael/atomic-emacs/pull/59 and released `0.6.0`.

**Comment by oggy** [comment]
I think we've solved everything here, so closing.
