### ISSUE TITLE
Comment block inserts ';' and comments that

### ISSUE THREAD

**Issue by nathanjohnson320** [avendael/atomic-emacs#65]
So given the following block
```
<link rel="import" href="tooltip.html">
<link rel="import" href="order-online.html">
<link rel="import" href="product-header.html">
<link rel="import" href="modal.html">
```

If I do the comment block command: `ctrl-alt-;` the end result is `<!-- ; -->`

**Comment by oggy** [comment]
I can't reproduce this with the latest versions, so assuming this is fixed, or that you had the wrong package (we bind `alt-;`, not `ctrl-alt-;` to `editor:toggle-line-comments`).

Let us know if you still think atomic-emacs is doing something wrong. Thanks!
