### ISSUE TITLE
When installed, arrow keys on cmd + shift + p OR cmd + p doesn't work

### ISSUE THREAD

**Issue by anildigital** [avendael/atomic-emacs#72]
When I enable/install atomic-emacs, arrow keys on cmd + shift + p OR cmd + p doesn't work.

**Comment by bradens** [comment]
:+1:

**Comment by bradens** [comment]
Downgrading to 0.6.0 fixes it

**Comment by anildigital** [comment]
@bradens how to downgrade it?

**Comment by anildigital** [comment]
@bradens okay found it. Done using 'apm install atomic-emacs@0.6.0'

**Comment by oggy** [comment]
I believe this was fixed -- please reopen if problems persist. Thanks!
