### ISSUE TITLE
Ctrl-E Doesn't Go to End of Line

### ISSUE THREAD

**Issue by dlandis** [avendael/atomic-emacs#74]
I just installed the new Atom 1.0 and this plugin on Windows 7.

Immediately noticed ctrl-e opens up the Find/Replace section at the bottom of the text editor instead of moving the cursor to the end of the line. 

I had a completely vanilla atom installed before installing this plugin.

**Comment by oggy** [comment]
Thanks for reporting this -- a fix has been merged and should go out next release.
