### ISSUE TITLE
set-mark is incompatible with snippets

### ISSUE THREAD

**Issue by ashiato45** [avendael/atomic-emacs#77]
Atom's snippets with "$1, $2, ..." have the problem that blanks are not properly selected when once atomic-emacs:set-mark called.  We can recover by calling atomicEmacs.keyboardQuit(event) with Esc key now.

**Comment by oggy** [comment]
Hi @ashiato45,

Apologies for the slow response here. Is this still happening?

I was convinced there was a problem earlier, but now I can't seem to find the problem (with Atom 1.2.4), so it might have been incidentally fixed. If you're still seeing this, can you please provide the key sequences to demonstrate the problem?

Thanks!

**Comment by ashiato45** [comment]
Hi, as you say the problem is already fixed.  Thank you very much!
