### ISSUE TITLE
Find Next is Superseded

### ISSUE THREAD

**Issue by mrphilroth** [avendael/atomic-emacs#78]
ctrl-s shows the find-and-replace window. Each successive time I press ctrl-s, the find-next behavior doesn't happen. Opening the Key Binding Resolver shows this:

![screen shot 2015-07-20 at 4 17 07 pm](https://cloud.githubusercontent.com/assets/2480909/8786228/d2ea66b2-2efa-11e5-9050-522d967edcfc.png)

So the desired behavior of find-and-replace:find-next is there, but it's superseded by the find-and-replace:show. But the window has already been shown! My focus is in the find-and-replace window, so I'm not sure why that more specific keybinding find-next isn't listed first here.

**Comment by oggy** [comment]
:+1: Thanks for the heads up!
