### ISSUE TITLE
atomic-emacs:backward-word is really slow

### ISSUE THREAD

**Issue by chhabrakadabra** [avendael/atomic-emacs#79]
I've always noticed that alt-b is really slow (takes a couple of seconds sometimes). Weirdly enough, alt-f is just fine. Equally weird is that ctrl-leftarrow and ctrl-rightarrow are very responsive too. I've tried looking at the dev tool and attempted to understand what's going on, but I'm not having much luck. Can you please help?

**Comment by oggy** [comment]
I'm guessing you have a package installed that has a binding which starts with `alt-b` (see #75). Search for "alt-b" in the settings pane under "Keybindings" to see where they may be.

Unless it's a core package providing this conflicting binding, I'm not inclined to add a workaround like we did for #75. You could perhaps add a personal binding to `alt-b alt-b`, or else fork the other package and modify the keybindings. Neither are great solutions, but without atom/atom-keymap#78, I can't think of a great alternative.

**Comment by chhabrakadabra** [comment]
Huh. You're right. Thanks for the help. I'm happy to modify the other interfering package.
