### ISSUE TITLE
Could you please add delete next char (delete-char)?

### ISSUE THREAD

**Issue by dlandis** [avendael/atomic-emacs#80]
I have my keymap.cson set up with:
      'ctrl-d': 'core:delete'

I think that overrode `find-and-replace:select-next`, but delete-char is a core emacs behavior so I think it makes sense to have it. `select-next` should probably be something else.

Thanks!

**Comment by jacmoe** [comment]
For the record: I like the `find-and-replace:select-next` command so I set it to `ctrl-alt-d` in my keymap.

Relatedly: `ctrl-d` is not listed in the keybindings - it is only listed in the keybindings configuration page inside of Atom. :)
