### ISSUE TITLE
Disabling and re-enabling package causes doubled navigation movement

### ISSUE THREAD

**Issue by johnjcamilleri** [avendael/atomic-emacs#81]
Here's a fun bug for you: if I disable the package and then re-enable it, all my navigation movements are doubled! So <kbd>ctrl-n</kbd> goes forward two lines etc. If dis/re-enable again, everything is tripled! Seems like you are forgetting to unregister something when the package is disabled.

**Comment by oggy** [comment]
You're exactly right -- thanks!
