### ISSUE TITLE
Request: cancel out of set-mark mode when copying

### ISSUE THREAD

**Issue by johnjcamilleri** [avendael/atomic-emacs#82]
This is a feature request: if I select a region with <kbd>ctrl-space</kbd> followed by navigation commands, and then copy it with <kbd>cmd-c</kbd>, the editor remains in set-mark mode. So if I then navigate to somewhere else, I first have to unset marking mode with <kbd>ctrl-g</kbd>. Is it possible to automatically exit out of this set-mark mode when using the copy command?

**Comment by oggy** [comment]
How about using `alt-w`?

The current behavior is actually the built-in Atom function. Like emacs, atomic-emacs, doesn't do anything to the command key. This way also feels more in line with other applications: e.g. in the notes app cmd-c doesn't deselect.

**Comment by johnjcamilleri** [comment]
Fair enough! I just rebound <kbd>cmd-c</kbd> in my personal `keymap.cson`, works great:

```
'atom-workspace atom-text-editor':
  'cmd-c': 'atomic-emacs:copy'
```
