### ISSUE TITLE
Alt->

### ISSUE THREAD

**Issue by mariusnita** [avendael/atomic-emacs#83]
I upgraded to the latest version in Atom and Alt-> (go to end of buffer) no longer works...

**Comment by mariusnita** [comment]
Alt-/ (undo) doesn't seem to work either. If I type some text and hit Alt-/, it doesn't work. However, in some cases it works. E.g. if I do Alt-t (transpose words), and then hit Alt-/, it will work.

**Comment by oggy** [comment]
Hmm, it's working for me, although I found the linter package added a binding sometime in the last month or so which currently overrides AE's. What do you see in the key binding resolver? (`command-.` on a mac)

Undo is `control-/`, not `alt-/`. Does that work better?

**Comment by oggy** [comment]
Closing as stale -- feel free to reopen if you think anything isn't working correctly. Thanks!
