### ISSUE TITLE
C-u SPC should stop marking after a copy

### ISSUE THREAD

**Issue by artagnon** [avendael/atomic-emacs#84]
C-u SPC, C-n, Cmd-C -- I should not have to C-g out now. When I copy something, I intend to go somewhere and paste it, not continue selecting text.

**Comment by oggy** [comment]
Hi @artagnon 

alt-w should do what you're after.

I'm inclined to leave cmd-c alone as this behavior is more consistent with other mac applications where cmd-c does not alter the selection. Of course, you can always bind the alt-w command (`atomic-emacs:copy`) if you'd prefer cmd-c to behave this way.

**Comment by artagnon** [comment]
Thanks, I understand the rationale, and will opt to override Cmd-C for myself.
