### ISSUE TITLE
Ctrl-/ produces a "whump" sound that's not in Cmd-z

### ISSUE THREAD

**Issue by artagnon** [avendael/atomic-emacs#85]
I can't seem to figure out why: when you bind some other key to core:undo, it produces a *whump* sound, unlike Cmd-z.

Update: It's only C-/; any other key bound to core:undo works fine.

**Comment by oggy** [comment]
Hi @artagnon, I'm not seeing this. Perhaps another package is binding `ctrl-/` -- does the key binding resolver (`cmd-.`) show anything else being run? What Atom version & OS are you running?

**Comment by artagnon** [comment]
Hi, it's 1.0.19 on my Macbook Pro (OS X 10.10), and git head on my iMac (OS X 10.10). I see this issue in both places, and it happens consistently. I checked Cmd-. and C-/ is only core:undo; C-_, which is bound to core:undo as well, doesn't produce the _whymp_; maybe the OS is producing the sound?

**Comment by oggy** [comment]
Yeah I suspect Mac OS is intercepting it somehow. If I switch to a blank space and hit ctrl-/ (or ctrl with almost anything) it whumps. I wonder if you have something under System Preferences -> Keyboard -> Shortcuts that binds something to ctrl-/?

If you disable atomic-emacs, or bind anything else in Atom to C-/, do you still get it? I can't imagine what atomic-emacs could be doing to cause it.

**Comment by artagnon** [comment]
This is an Atom Mac bug then. I'll file the bug there, as appropriate. Thanks for helping me through this.
