### ISSUE TITLE
alt on ubuntu opens menu

### ISSUE THREAD

**Issue by uptownhr** [avendael/atomic-emacs#90]
Not sure if i'm not doing something correctly but I can't use any of the alt bindings as it toggles the menu. Anyway to disable?

**Comment by oggy** [comment]
I think this is more of an Atom issue than an atomic-emacs one. There's some discussion as well as a workaround [here](https://discuss.atom.io/t/alt-key-menu-bar-interaction-overrides-shortuts/9192), and a Github issue [here](https://github.com/atom/atom/issues/4057). Hopefully Atom will give a way to disable or change the menubar shortcuts soon!
