### ISSUE TITLE
Make ctrl-l behavior same as emacs

### ISSUE THREAD

**Issue by enelson** [avendael/atomic-emacs#91]
Would it be possible to more closely model the ctrl-l command to emacs behavior? Specifically, right now it only recents the current line. But in emacs, if you keep hitting it, it will take the current line to the top and to the bottom as well. It just cycles through top, middle, bottom. Would love that feature. By the way, this is a killer atom package. Well done!

**Comment by enelson** [comment]
Hi @oggy, I assume this means no? :)

**Comment by oggy** [comment]
@enelson Nope, there's a commit above -- maybe the email notification didn't show it. Pushed version 0.8.0. :)

**Comment by enelson** [comment]
@oggy  Oh nice! Thanks man. I've come to love this plugin in combination with ensime for Atom. Great work!
