### ISSUE TITLE
kill/copy whole line when region is empty

### ISSUE THREAD

**Issue by mminkoff** [avendael/atomic-emacs#94]
I'm so happy to have the kill ring - thank you!  One thing - before this update killing without a region selected defaulted to killing the whole current line (different from killing from the cursor to the end of the line).  Is there a way to restore that?

**Comment by oggy** [comment]
Killing forward from the cursor is what emacs does, so I think it's the right behavior for atomic-emacs.

If you want to override this, you could rebind the key to the Atom default in your personal keymap. e.g.:

    'atom-workspace atom-text-editor':
      'ctrl-k': 'editor:cut-to-end-of-line'

That'll just cut the text though, not add it to the kill ring. To do that you'd need to define your own command that looks like 'atomic-emacs:kill-line'. AtomicEmacs exports all its modules so you should be able to write such a command yourself.

**Comment by mminkoff** [comment]
fair enough - looks like I'm using `whole-line-or-region.el` - more info here: http://www.emacswiki.org/emacs/WholeLineOrRegion

It's really handy.  Not as handy as the kill ring though, so I'm not just going to rebind the key.  Any further hints for how to add this myself would be awesome, but thanks either way.
