### ISSUE TITLE
Kill line is slow

### ISSUE THREAD

**Issue by stufkan** [avendael/atomic-emacs#96]
When I use my ctrl+k binding the operation takes an annoying amount of time to execute.

**Comment by bostrt** [comment]
I'm having the same issue. A (bad) workaround is to hit ctrl-k ctrl-g. The issue seems to be atomic waiting for a secondary key to be hit since there are other default keybindings starting with ctrl-k. When a timeout is reached, it performs the kill line command.

Some input from atomic-emacs devs would be great since kill line is such a fundamental feature.

**Comment by bostrt** [comment]
@stufkan Install the package [disable-keybindings](https://atom.io/packages/disable-keybindings). Once installed, go to settings for that plugin, Enable `All Community Packages`, add "atomic-emacs" into `Except Community Packages`, and finally "ctrl-k" into `Prefix Keys`. 

ctrl-k works without the delay after that.

**Comment by crispamares** [comment]
I solved this issue by adding this to the keymap.cson file:

```cson
'body':
 'ctrl-x': 'unset!'  # No cut
 'ctrl-k up': 'unset!'
 'ctrl-k down': 'unset!'
 'ctrl-k left': 'unset!'
 'ctrl-k right': 'unset!'
 'ctrl-k ctrl-w': 'unset!'
 'ctrl-k ctrl-alt-w': 'unset!'
 'ctrl-k ctrl-p': 'unset!'
 'ctrl-k ctrl-n': 'unset!'
 'ctrl-k ctrl-up': 'unset!'
 'ctrl-k ctrl-down': 'unset!'
 'ctrl-k ctrl-left': 'unset!'
 'ctrl-k ctrl-right': 'unset!'
'atom-workspace atom-text-editor':
 'ctrl-k ctrl-u': 'unset!'
 'ctrl-k ctrl-l': 'unset!'
'atom-workspace atom-text-editor:not([mini])':
 'ctrl-k ctrl-0': 'unset!'
 'ctrl-k ctrl-1': 'unset!'
 'ctrl-k ctrl-2': 'unset!'
 'ctrl-k ctrl-3': 'unset!'
 'ctrl-k ctrl-4': 'unset!'
 'ctrl-k ctrl-5': 'unset!'
 'ctrl-k ctrl-6': 'unset!'
 'ctrl-k ctrl-7': 'unset!'
 'ctrl-k ctrl-8': 'unset!'
 'ctrl-k ctrl-9': 'unset!'
'.platform-darwin, .platform-linux': 'ctrl-k ctrl-b': 'unset!'
'.platform-darwin .tree-view, .platform-linux .tree-view':
 'ctrl-k right': 'unset!'
 'ctrl-k l': 'unset!'
 'ctrl-k left': 'unset!'
 'ctrl-k h': 'unset!'
 'ctrl-k up': 'unset!'
 'ctrl-k k': 'unset!'
 'ctrl-k down': 'unset!'
 'ctrl-k j': 'unset!'
'.platform-darwin atom-text-editor, .platform-linux atom-text-editor':
 'ctrl-k ctrl-d': 'unset!'

```

**Comment by oggy** [comment]
Thanks for the solutions @bostrt and @crispamares .

This has come up before, and I think the general issue of key binding collisions between packages, and between package & core is something of an [unsolved problem](https://discuss.atom.io/t/key-binding-hell/12075).

In the meantime, I've added a note to the README about this.

**Comment by jazzlw** [comment]
A note in the readme explaining how to set up disable keybindings, as @bostrt above, would be great. It's not obvious.
