### ISSUE TITLE
Selection disappears when moving the cursor forward from EOF (or backward from BOF)

### ISSUE THREAD

**Issue by itiut** [avendael/atomic-emacs#98]
Reproduce procedure:

1. Activate the mark in any position
2. Move to EOF
3. Move the cursor forward by `forward-char` or something
4. Selection disappears

This also happens when moving the cursor backward from BOF.

I found that the `onDidChangePosition` callback in `mark.coffee` is not triggered when selection disappears. I think it's because commands to move cursors are called but the cursor position is not actually changed.

**Comment by oggy** [comment]
Good catch -- fixed!
